### ISSUE TITLE
release Arquillian Governor 1.0.1 / 1.1.0

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-governor#15]
@aslakknutsen please do that, i think @alesj finds it useful to have it cut, not sure about the version, it does not matter, only ignore module is added

**Comment by aslakknutsen** [comment]
Yeah, I'll cut a release tonight

**Comment by alesj** [comment]
@smiklosovic @aslakknutsen tnx guys!

**Comment by aslakknutsen** [comment]
Pushed live
