### ISSUE TITLE
Add checkstyle plugin

### ISSUE THREAD

**Issue by basovnik** [arquillian/arquillian-governor#30]

**Comment by basovnik** [comment]
@smiklosovic What do you think about adding the following checkers?

http://checkstyle.sourceforge.net/config_coding.html#FinalLocalVariable
http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly

It would require quite more changes...

I would add support for [Travis-CI](https://travis-ci.org) to check coding style automatically before merging...

**Comment by smiklosovic** [comment]
agree with both, refactor it as you wish
