### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by basovnik** [arquillian/arquillian-governor#31]
Blocked by #30.

@smiklosovic Could you please register arquillian-governor project in [Travis-CI](https://travis-ci.org/)? Then add the following file to the root of git repository: 
https://gist.github.com/basovnik/31efdc02e1462874757cef66f1aa5857

**Comment by smiklosovic** [comment]
why you would skip tests?

**Comment by basovnik** [comment]
I was using my own credentials for GitHub and Jira so I thought it is not possible to execute tests without some extra system properties. But I tried it now and it works out of the box. So do not skip tests.

**Comment by smiklosovic** [comment]
https://travis-ci.org/arquillian/arquillian-governor

@basovnik could you repair that, please?

**Comment by basovnik** [comment]
I am sorry I did not resolve git conflict correctly - https://github.com/arquillian/arquillian-governor/pull/29#issuecomment-237314391. I accidently deleted checkstyle configuration.

Fix is here - https://github.com/arquillian/arquillian-governor/pull/32.
