### ISSUE TITLE
Make all log messages configurable

### ISSUE THREAD

**Issue by basovnik** [arquillian/arquillian-governor#33]
- Do not use `System.out.println`
- Information about governor configuration should no have `INFO` log level.

**Comment by bartoszmajsak** [comment]
This is something I would like to have a clarification on as well. I've noticed that in some modules (and probably Core if I'm not mistaken) we have started using `sout` instead of `jul`. What is the rationale here? Maybe @aslakknutsen, @smiklosovic or @lordofthejars can shed some light

**Comment by smiklosovic** [comment]
i try to log by logger, if done otherwise, it is bad on my side. i can not speak for others

**Comment by basovnik** [comment]
@bartoszmajsak I think we should definitely use loggers for logging. Why? We should allow user to filter logging messages according to the logging level. Next point is that I would prefer *slf4j* before `java.util.logging`. Libraries should let user to choose custom implementation of logging framework [1].

[1] http://slf4j.org/faq.html#when
