### ISSUE TITLE
InvalidCheck for getPlainAdoc

### ISSUE THREAD

**Issue by kpiwko** [arquillian/arquillian-governor#4]
If configuration for skipper is missing, it fails completely:

The reason is that checks check for null, however empty string is returned instead. Then, it tries to create a file which is actually a target directory and then IOException is thrown but hidden because of #3

https://github.com/arquillian/arquillian-governor/blob/0414ad3ca53d1d0e24142b6e07e0b985311ab705/skipper/src/main/java/org/arquillian/extension/governor/skipper/config/SkipperConfiguration.java#L29

**Comment by smiklosovic** [comment]
https://github.com/arquillian/arquillian-governor/commit/3b900e2e0bf04dc44239ed79d65556dae82d3072
