### ISSUE TITLE
Steps defined as an array

### ISSUE THREAD

**Issue by kpiwko** [arquillian/arquillian-governor#6]
Any reason why steps are not an array?

https://github.com/arquillian/arquillian-governor/blob/9999dc3f50f223c3065cd677ed5bb1a549b71e35/arquillian-governor/skipper/src/main/java/org/arquillian/extension/governor/skipper/api/TestSpec.java#L61

**Comment by smiklosovic** [comment]
https://github.com/arquillian/arquillian-governor/commit/838889aaf62c11c46db6e192917047226af088b7
